/**
 * What's New ships a bounded number of entries.
 *
 * One fragment lands per user-facing PR, and at this repo's rate that was
 * 1,558 of them inside two months: 346 KB of strings compiled into the Hermes
 * bytecode, downloaded and kept by every user, on a trajectory of several MB a
 * year for a list nobody scrolls to the end of. `build-patch-notes.js` now
 * writes only the newest `SHIPPED_ENTRY_LIMIT` of them.
 *
 * The fragments are untouched — `src/patchNotes/entries/` is still the full
 * record, and raising the limit brings the older ones back — so nothing here
 * is lost, only unshipped. Which means the cap is also invisible: drop the
 * slice and the app works perfectly, just fatter, with the only signal being
 * the size of a bundle nobody measures per PR. Hence this.
 *
 * `patchNotesData.ts` is generated and gitignored, regenerated by `pretest`,
 * so the array read here is always the one a build would ship.
 */
import { readFileSync } from 'fs';
import { join } from 'path';

import { patchNotes } from '../utils/patchNotes';

/** The limit as the generator actually holds it, not a second copy to drift from. */
function shippedEntryLimit(): number {
  const script = readFileSync(join(__dirname, '..', '..', 'scripts', 'build-patch-notes.js'), 'utf8');
  const match = script.match(/^const SHIPPED_ENTRY_LIMIT = (\d+);$/m);
  if (!match) throw new Error('build-patch-notes.js no longer declares SHIPPED_ENTRY_LIMIT');
  return Number(match[1]);
}

describe('shipped patch notes', () => {
  it('ships no more than the generator says', () => {
    expect(patchNotes.length).toBeLessThanOrEqual(shippedEntryLimit());
  });

  it('ships enough to be worth opening', () => {
    // Guards the other direction: a generator bug that emitted two entries
    // would satisfy the cap and gut the feature.
    expect(patchNotes.length).toBeGreaterThan(50);
  });

  it('keeps the newest entries, not an arbitrary slice', () => {
    // Dates descending. The cap takes from the front, so a sort that broke
    // would ship whichever entries happened to be first.
    const dates = patchNotes.map(n => n.date);
    expect([...dates].sort().reverse()).toEqual(dates);
  });

  it('gives every entry a unique id, a message and a date', () => {
    const ids = patchNotes.map(n => n.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const note of patchNotes) {
      expect(note.message.trim()).not.toBe('');
      expect(note.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
});
